[workspace]
members = [
    "packages/yewflow",

    "examples/simple",
    "examples/stress-test",
    "examples/bezier",
]
resolver = "2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"