[package]
name = "yewflow"
version = "0.1.0"
edition = "2021"
description = "A flowchart library for Yew, inspired by React Flow"
readme = "README.md"
repository = "https://github.com/nmattela/yewflow"
license = "MIT"
keywords = ["yew", "trunk", "flowchart"]
categories = ["gui", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version="0.21" }
gloo-console = "0.3.0"
wasm-bindgen = "0.2"
implicit-clone = { version="0.4.1", features=["map"] }
yew-hooks = "0.3.0"
js-sys = "0.3.64"

[dev-dependencies]
yew = { features = ["csr"]}

[dependencies.web-sys]
version = "0.3"
# We need to enable all the web-sys features we want to use!
features = [
    "console",
    "Document",
    "HtmlElement",
    "MouseEvent",
    "DomRect",
    "EventTarget",
    "Element",
    "Window",
    "MutationObserver",
    "MutationRecord",
    "Node",
    "MutationObserverInit",
    "HtmlCollection",
    "WheelEvent"
]